### ISSUE TITLE
Rely on "Auto-cancel redundant pipelines"

### ISSUE THREAD

**Issue by dancysoft** [yaoyuannnn/gitlab-gerrit-review#25]
To simplify the code and reduce API calls, I propose relying on the behavior of [the Auto-cancel redundant pipelines CI/CD setting](https://docs.gitlab.com/ee/ci/pipelines/settings.html#auto-cancel-redundant-pipelines) instead of using `cancel_prev_pipelines()`.

**Comment by yaoyuannnn** [comment]
I like this. I vaguely remember GitLab doesn't cancel pipelines in some cases. Let's rely on the GItLab feature and if it turns out to be an issue, we can add `cancel_prev_pipelines()` back and add an option in the `.gitreview` to optionally run it.

**Comment by dancysoft** [comment]
> I like this. I vaguely remember GitLab doesn't cancel pipelines in some cases. 

I know that one requirement is that jobs must be marked [interruptible](https://docs.gitlab.com/ee/ci/yaml/#interruptible).

**Comment by yaoyuannnn** [comment]
I see. Looks like the GitLab repos I contribute to are not doing that. We may want to use a config flag for running `cancel_prev_pipelines()`, which by default is disabled.

**Comment by dancysoft** [comment]
I'm retracting this proposal.  The existing approach is more likely to be useful to users.
