### ISSUE TITLE
Make commit message in merge request description more visually prominent

### ISSUE THREAD

**Issue by kostajh** [yaoyuannnn/gitlab-gerrit-review#40]
Following up from https://github.com/yaoyuannnn/gerritlab/pull/31, it would be neat to have the merge request description kept in sync with the commit message contents. (Maybe the "Related MRs" part could go below the commit message.)

That would feel more Gerrit-like and intuitive, IMO.

**Comment by yaoyuannnn** [comment]
Maybe I'm missing something, isn't the MR chain currently shown below the commit message? @dancysoft for reference.

**Comment by yaoyuannnn** [comment]
Did you mean we add the MR chain information to the actual commit message (not the MR description)?

**Comment by dancysoft** [comment]
> Following up from #31, it would be neat to have the merge request description kept in sync with the commit message contents. (Maybe the "Related MRs" part could go below the commit message.)

Hey Kosta.  This is exactly how it works right now.  Note that you have to reload the MR page in the browser to see the updated description.  It does not automatically refresh (although other parts of the MR UI do change when something external makes an update... it's confusing).

**Comment by kostajh** [comment]
> Did you mean we add the MR chain information to the actual commit message (not the MR description)?

No, sorry,  I meant, update the MR description and title each time that the commit message contents change. As @dancysoft points out, this is already happening:

> > Following up from #31, it would be neat to have the merge request description kept in sync with the commit message contents. (Maybe the "Related MRs" part could go below the commit message.)
> 
> Hey Kosta. This is exactly how it works right now. Note that you have to reload the MR page in the browser to see the updated description. It does not automatically refresh (although other parts of the MR UI do change when something external makes an update... it's confusing).

Ah, I see. I think I somehow missed the giant `<h1>` at the top of the page 🤦 , maybe because it's separated by the tabs (Overview, Commits, Pipelines, Changes) from the rest of the content below, and I was expecting to see the `Change-Id` in the merge request description field (although it makes sense to hide`Change-Id` as extraneous information).

Maybe it's worth experimenting with including the commit message subject in the body of the updated MR in addition to its title, so it's more obvious? And/or wrapping the commit message that's in the MR description with the ``` formatting block, so it stands out more?

**Comment by dancysoft** [comment]
> Maybe it's worth experimenting with including the commit message subject in the body of the updated MR in addition to its title, so it's more obvious? And/or wrapping the commit message that's in the MR description with the ``` formatting block, so it stands out more?

I'm not in favor of these ideas.
1) The commit message subject already becomes the title of the MR and it is displayed prominently with large bold font at the top of the page.   
2) Wrapping the commit message in ``` would prevent users from using markdown in their commit messages.  

Overall, compensating for the unfamiliar GitLab UI is not the purpose of Gerritlab.

**Comment by kostajh** [comment]
Hmm, how about a horizontal line (`---`) for separating commit message from the metadata?

<img width="823" alt="image" src="https://github.com/yaoyuannnn/gerritlab/assets/208893/701a3f92-b186-462a-8743-28fdacb8ca9e">

compared to

<img width="823" alt="image" src="https://github.com/yaoyuannnn/gerritlab/assets/208893/db40c5e9-1491-4159-8f45-33005ce57e92">

**Comment by dancysoft** [comment]
That seems reasonable to me.  If you make a PR I'm happy to test it.
