### ISSUE TITLE
Proposal for revised branch naming

### ISSUE THREAD

**Issue by dancysoft** [yaoyuannnn/gitlab-gerrit-review#53]
Right now gerritlab pushes commits to branches named after the local branch (or a name supplied on the command line).  I suggest a new scheme for naming branches:

`<final-target-branch-name>-<fullchangeid>`

final-target-branch-name comes from `target_branch` in `.gitreview`, unless an override is supplied on the command line.

Advantages:
* The remote branch names never depend on the developer's local branch name.  This means you can rename your local branch without worrying about a new set of MRs being created.
* Using the full Change-Id deals with #39

**Comment by dancysoft** [comment]
@yaoyuannnn @thcipriani What do you think?

**Comment by yaoyuannnn** [comment]
This is a nice idea!

**Comment by kostajh** [comment]
> Right now gerritlab pushes commits to branches named after the local branch (or a name supplied on the command line). I suggest a new scheme for naming branches:
> 
> `<final-target-branch-name>-<fullchangeid>`
> 
> final-target-branch-name comes from `target_branch` in `.gitreview`, unless an override is supplied on the command line.
> 
> Advantages:
> 
>     * The remote branch names never depend on the developer's local branch name.  This means you can rename your local branch without worrying about a new set of MRs being created.
> 
>     * Using the full Change-Id deals with [Increase the number of characters of the Change-Id used to generate the source branch name #39](https://github.com/yaoyuannnn/gerritlab/issues/39)

I think this would also address my concerns in https://github.com/yaoyuannnn/gerritlab/issues/49#issuecomment-1761389045.

With your PR, does it mean that one could use `git cherry-pick` to create a stack of MRs from two unrelated MRs?

**Comment by dancysoft** [comment]
> I think this would also address my concerns in [#49 (comment)](https://github.com/yaoyuannnn/gerritlab/issues/49#issuecomment-1761389045).

Agreed
 
> With your PR, does it mean that one could use `git cherry-pick` to create a stack of MRs from two unrelated MRs?

If you're asking if this allows having a cherry-pick of a given commit (with the same Change-Id) for two different target branches, the answer is yes.  If you're asking something else, I'll need you to flesh out the scenario a bit more.
