### ISSUE TITLE
Minimum GitLab version?

### ISSUE THREAD

**Issue by WhosNickDoglio** [yaoyuannnn/gitlab-gerrit-review#71]
Hello! I saw this linked in a stacking MR article the other day and wanted to give it a try but I've been running into issues with the version (15.5.9-ee) of GitLab my company uses internally.

trying to run `git lab` to update an MR gave me this error 

```
Traceback (most recent call last):
  File "/Users/nicholasdo/Library/Python/3.9/bin/git-lab", line 8, in <module>
    sys.exit(main())
  File "/Users/nicholasdo/Library/Python/3.9/lib/python/site-packages/gerritlab/main.py", line 361, in main
    create_merge_requests(repo, remote, final_branch)
  File "/Users/nicholasdo/Library/Python/3.9/lib/python/site-packages/gerritlab/main.py", line 266, in create_merge_requests
    c.mr.wait_until_stable(c)
  File "/Users/nicholasdo/Library/Python/3.9/lib/python/site-packages/gerritlab/merge_request.py", line 249, in wait_until_stable
    if self._prepared_at and self._sha == commit.commit.hexsha:
AttributeError: 'MergeRequest' object has no attribute '_prepared_at'
```

I don't think the `prepared_at` property exists in the version of GitLab we're using 😿

**Comment by dancysoft** [comment]
Sorry about that @WhosNickDoglio!  Unfortunately I don't have access to a 15.5.9-ee system to test against. Can you provide a sample of what `curl https://GITLABURL/api/v4/projects/PROJECTID/merge_requests/MRID` returns (replacing the placeholders as appropriate)?

**Comment by thcipriani** [comment]
oh bother. Yes, it does look `prepared_at` was added to the merge request API recently ([version 16.1](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122001/diffs)).

**Comment by thcipriani** [comment]
Maybe we should update our documentation to include the minimum version.

And I think I would propose we strive to match features to the [GitLab product security release cycle](https://about.gitlab.com/security/faq/#gitlab-product-security).

As of today, that would mean, maintaining compatibility with the last three `major.minor` releases of the GitLab product. So, based on [release timeline](https://about.gitlab.com/releases/) that would be:
- 16.5
- 16.4
- 16.3

So, actions:
- Document base version
- Think really hard if we want to introduce a feature that is incompatible with the last three `major.minor` GitLab releases

**Comment by WhosNickDoglio** [comment]
Thank you everyone for the quick response! 

@dancysoft This is the response you asked for [response.json](https://github.com/yaoyuannnn/gerritlab/files/13365831/response.json)
