### ISSUE TITLE
How to rebase/modify an mr

### ISSUE THREAD

**Issue by MadoScientist97** [yaoyuannnn/gitlab-gerrit-review#83]
Say I have a bunch of MRs, and now a commit/MR receives review comments, what is the correct way to do the change, commit and then rebase?

I mean does the subcommand provides any way to do this? What happens if I manually rebase does the older MR gets removed automatically?

**Comment by yaoyuannnn** [comment]
A commit is associated with an MR using the ChangeId attached to the commit message. You should just do rebase as usual and the MRs will be automatically updated.

**Comment by MadoScientist97** [comment]
Thanks yep just rebasing did seem to automatically put it in the right order in the list of MRs
